version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: cybersentinel
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://root:rootpassword@db:5432/cybersentinel?schema=public"
      JWT_SECRET: "supersecretjwtkey"
    depends_on:
      - db

volumes:
  pgdata:
